### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by fdo13100** [jbelien/OVH-Cloud-Snapshot#1]
Hi jbelien

I have this error message (please see attachment file ) at the step "Installation"
I use a CentOS release 6.9 (Final)
![screenshot](https://user-images.githubusercontent.com/32484697/31125654-4a3c45cc-a849-11e7-9abb-6b8c2e28a802.PNG)

thx !

**Comment by jbelien** [comment]
My mistake, I indeed forget to publish a release !

The command `composer create-project jbelien/ovh-cloud-snapshot` should now work and install `v1.0.0` !

**Comment by fdo13100** [comment]
Much better  ! :)
It woks perfectly. Thank you so much for your help.

**Comment by jbelien** [comment]
Thank you :)

Feel free to propose ideas or report things that are not working ! 👍
