### ISSUE TITLE
Add rotation parameter

### ISSUE THREAD

**Issue by jbelien** [jbelien/OVH-Cloud-Snapshot#2]
Add ability to rotate snapshots so it deletes "old" snapshots !

**Comment by fdo13100** [comment]
It will be very useful :)

**Comment by jbelien** [comment]
I'll try to add that as soon as I have a little of free time :)

**Comment by jbelien** [comment]
Fixed by 8a8b7309d46cfbcd60032972deb3022216aeeb7c ! 🎉
